/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.asn1bean.compiler.tagging_test;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ChoiceOfRenamedUntaggedSequence implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	private byte[] code = null;
	private BerInteger myInteger = null;
	private RenamedUntaggedSequence renamedUntaggedSequence = null;
	private BerBoolean myBoolean = null;
	
	public ChoiceOfRenamedUntaggedSequence() {
	}

	public ChoiceOfRenamedUntaggedSequence(byte[] code) {
		this.code = code;
	}

	public void setMyInteger(BerInteger myInteger) {
		this.myInteger = myInteger;
	}

	public BerInteger getMyInteger() {
		return myInteger;
	}

	public void setRenamedUntaggedSequence(RenamedUntaggedSequence renamedUntaggedSequence) {
		this.renamedUntaggedSequence = renamedUntaggedSequence;
	}

	public RenamedUntaggedSequence getRenamedUntaggedSequence() {
		return renamedUntaggedSequence;
	}

	public void setMyBoolean(BerBoolean myBoolean) {
		this.myBoolean = myBoolean;
	}

	public BerBoolean getMyBoolean() {
		return myBoolean;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			return code.length;
		}

		int codeLength = 0;
		if (myBoolean != null) {
			codeLength += myBoolean.encode(reverseOS, true);
			return codeLength;
		}
		
		if (renamedUntaggedSequence != null) {
			codeLength += renamedUntaggedSequence.encode(reverseOS, true);
			return codeLength;
		}
		
		if (myInteger != null) {
			codeLength += myInteger.encode(reverseOS, true);
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int tlvByteCount = 0;
		boolean tagWasPassed = (berTag != null);

		if (berTag == null) {
			berTag = new BerTag();
			tlvByteCount += berTag.decode(is);
		}

		if (berTag.equals(BerInteger.tag)) {
			myInteger = new BerInteger();
			tlvByteCount += myInteger.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(RenamedUntaggedSequence.tag)) {
			renamedUntaggedSequence = new RenamedUntaggedSequence();
			tlvByteCount += renamedUntaggedSequence.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(BerBoolean.tag)) {
			myBoolean = new BerBoolean();
			tlvByteCount += myBoolean.decode(is, false);
			return tlvByteCount;
		}

		if (tagWasPassed) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (myInteger != null) {
			sb.append("myInteger: ").append(myInteger);
			return;
		}

		if (renamedUntaggedSequence != null) {
			sb.append("renamedUntaggedSequence: ");
			renamedUntaggedSequence.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (myBoolean != null) {
			sb.append("myBoolean: ").append(myBoolean);
			return;
		}

		sb.append("<none>");
	}

}

