/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.asn1bean.compiler.pedefinitions;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class UInt31 extends BerInteger {

	private static final long serialVersionUID = 1L;

	public UInt31() {
	}

	public UInt31(byte[] code) {
		super(code);
	}

	public UInt31(BigInteger value) {
		super(value);
	}

	public UInt31(long value) {
		super(value);
	}

}
