/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.asn1bean.compiler.modules.module2;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class TestChoice implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	private byte[] code = null;
	private BerInteger element1 = null;
	private BerInteger element2 = null;
	
	public TestChoice() {
	}

	public TestChoice(byte[] code) {
		this.code = code;
	}

	public void setElement1(BerInteger element1) {
		this.element1 = element1;
	}

	public BerInteger getElement1() {
		return element1;
	}

	public void setElement2(BerInteger element2) {
		this.element2 = element2;
	}

	public BerInteger getElement2() {
		return element2;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			return code.length;
		}

		int codeLength = 0;
		if (element2 != null) {
			codeLength += element2.encode(reverseOS, true);
			return codeLength;
		}
		
		if (element1 != null) {
			codeLength += element1.encode(reverseOS, true);
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int tlvByteCount = 0;
		boolean tagWasPassed = (berTag != null);

		if (berTag == null) {
			berTag = new BerTag();
			tlvByteCount += berTag.decode(is);
		}

		if (berTag.equals(BerInteger.tag)) {
			element1 = new BerInteger();
			tlvByteCount += element1.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(BerInteger.tag)) {
			element2 = new BerInteger();
			tlvByteCount += element2.decode(is, false);
			return tlvByteCount;
		}

		if (tagWasPassed) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (element1 != null) {
			sb.append("element1: ").append(element1);
			return;
		}

		if (element2 != null) {
			sb.append("element2: ").append(element2);
			return;
		}

		sb.append("<none>");
	}

}

